spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 39.96.52.99:8848
    
server:
  port: 8201

      
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#---
#spring:
#  profiles: order1
#server:
#  port: 8201
#---
#spring:
#  profiles: order2
#server:
#  port: 8202

